
services:
  api-debugger:
    image: api-debugger:latest
    container_name: api-debugger
    volumes: [./config.yaml:/etc/api-debugger/config.yaml]
    ports: [8080:8080]
    command: -config=/etc/api-debugger/config.yaml
