
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main cmd/api-debugger/main.go"
  bin = "./tmp/main"
  args_bin = [
    "--config-file=config.yaml",
    "--log-level=DEBUG"
  ]
  include_ext = ["go", "tmpl"]
  exclude_dir = ["node_modules"]
  exclude_unchanged = true
  delay = 1000
  poll = false
  rerun = false
  send_interrupt = false
  stop_on_error = true
  log = "air.log"

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
