
environment_info:
  prod: live application used by customers
  dev: used for development
headers:
  Content-Type:
    # contents of this section describe an "InputField"
    description: headers in root section apply to all requests
    # type: how user may input value
    # one of "text", "number" or "dropdown"
    type: dropdown
    # options: only applicable if dropdown was picked, otherwise ignored
    options:
      - application/json
      - text/html
    # default: initial value of InputField
    default: application/json
    # locked: if true will be displayed with input disabled
    locked: false
services:
  some-service:
    description: this services does something
    #< can define headers, apply to all requests of service
    environments:
      # if environment_info can be mapped it will be displayed
      prod: &prod-base
        url: localhost:8080
        paths: &prod-paths
          /:
            description: root handler path
            methods:
              GET:
                description: serves the home page
      dev:
        # use yaml anchors to copy information from other environments
        <<: *prod-base
        #< can define headers, apply to all requests of environment
        #< usually "url" should be overridden here
        paths:
          <<: *prod-paths
          /hello/{name}:
            description: path for personalized greetings
            #< can define headers, apply to all methods of path
            variables:
              name: # InputField
                description: name that will be greeted
                type: text
                default: Gopher
                locked: false
            methods:
              GET:
                description: greets the specified name
                #< can define headers, apply to this specific request
                #< can define "payload", which is an InputField
